### ISSUE TITLE
Show Git Branch with Remote Tools

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [wisetime-io/vscode-branch-in-window-title#12] opened 2022-03-31 07:46 UTC
For local folders, the extension works fine as expected. However, for remote folders (via Remote-SSH in my case), it doesn't show the branch information. I guess this needs to be handled explicitly. Would it be possible to extend the extension to support that as well?

**Comment by koenlek** [comment] 2022-06-25 01:07
Same here

**Comment by jiakuan** [comment] 2022-07-04 08:57
When a project is opened from Remote-SSH, no workspace information available through [vscode api](https://code.visualstudio.com/api/references/vscode-api).

```
  console.log("remoteName: " + JSON.stringify(vscode.env.remoteName));
  console.log("workspaceFolders: " + JSON.stringify(vscode.workspace.workspaceFolders));
```

It prints this output:

```
remoteName: "ssh-remote"
workspaceFolders: undefined
```

I went through the [vscode api](https://code.visualstudio.com/api/references/vscode-api), but didn’t find anything related to the Remote workspaces.

Then, I thought to check the source code of the Remote-SSH extension, so we should be able to know how it works. But the Remote-SSH extension is closed source.

Will need to think and investigate more about a possible way to obtain the remote workspace info.

References:

* https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source
* [Where's the actual Remote-SSH source code repo on github?](https://stackoverflow.com/questions/55979489/wheres-the-actual-remote-ssh-source-code-repo-on-github) 
* [Source repo?CLOSED](https://github.com/Microsoft/vscode-remote-release/issues/30)

**Comment by dslijepcevic** [comment] 2023-03-09 10:32
Hmm, did you try asking [here](https://github.com/microsoft/vscode-remote-release/issues)? If it is not possible, then there should be a feature request at least.

**Comment by jiakuan** [comment] 2023-03-09 11:07
No I haven't asked there yet. Given the closed source nature, I doubt if there will be a quick resolution in the near future.

However, it still seems a good idea to try asking in their issue list.

**Comment by AnrDaemon** [comment] 2024-03-12 11:23
Can you try a local build of #23 to see if it is resolved there as well?

**Comment by vyshane** [comment] 2024-05-07 01:23
We have just released [v0.2.0](https://github.com/wisetime-io/vscode-branch-in-window-title/releases/tag/v0.2.0). Can you please check if the issue is resolved?

**Comment by koenlek** [comment] 2024-05-07 06:01
It mostly works, but I ran into a bug. I was trying out the settings a bit ("Branch Template" and "Branch Name is Prefix") and noticed that after I changed the setting, it would sometimes start repeating injected the prefix.

I tried 3 different settings and used `Developer: Reload Window` to apply, and now I have:

`[develop] - [develop foo] myfile.txt - my_workspace_name (Workspace) [SSH: my_hostname] - [develop]`

This bug only seems to have when changing a setting and then reloading the window. If I reload again, it doesn't get better or worse. So I guess just closing VS Code and restarting it should fix it as long as I don't touch those extension settings anymore.

**Comment by koenlek** [comment] 2024-05-07 14:32
Restarting VS Code doesn't fix it. I still have my branch name tripled in my title.

**Comment by AnrDaemon** [comment] 2024-05-08 15:52
Please edit your workspace title and remove any references to the branch name, then reload window.
Since VS Code does not offer an API to manipulate window title in a fool-proof way, the extension relies on a hack to make it work.

**Comment by koenlek** [comment] 2024-05-08 16:10
Seems like that works. Thanks!

**Closed** 2024-05-08 23:54 UTC
